// export const INCREMENT = 'INCREMENT';
// export const DECREMENT = 'DECREMENT';
// export const INPUT_TEXT = 'INPUT_TEXT';
//export const COMM_CREATE = 'COMM_CREATE';
export const MASKPOINT_CREATE = 'MASSDK_CREATE';
export const STATSAVE_CREATE = 'STATSAVE_CREATE';
//export const MASSROUTE_CREATE = 'MASSROUTE_CREATE';
//export const COORDINATES_CREATE = 'COORDINATES_CREATE';
